version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: my_db
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=secretpassword
    - POSTGRES_DB=postgres
  app :
    container_name: my_app
    command: sleep infinity
    build: ./app/