version: "3.8"

networks:
  my_network:
    external: true

services:
  postgres:
    image: postgres:latest
    container_name: my_db
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=secretpassword
    - POSTGRES_DB=postgres
    networks:
    - my_network
  app :
    container_name: my_app
    command: sleep infinity
    networks:
      - my_network
    build: ./app/